`define NUM_NODES 1725

`define NODE_vcc 657
`define NODE_vss 558
`define NODE_cp1 710
`define NODE_cp2 943

`define NODE_res 159
`define NODE_rw 1156
`define NODE_db0 1005
`define NODE_db1 82
`define NODE_db3 650
`define NODE_db2 945
`define NODE_db5 175
`define NODE_db4 1393
`define NODE_db7 1349
`define NODE_db6 1591
`define NODE_ab0 268
`define NODE_ab1 451
`define NODE_ab2 1340
`define NODE_ab3 211
`define NODE_ab4 435
`define NODE_ab5 736
`define NODE_ab6 887
`define NODE_ab7 1493
`define NODE_ab8 230
`define NODE_ab9 148
`define NODE_ab12 1237
`define NODE_ab13 349
`define NODE_ab10 1443
`define NODE_ab11 399
`define NODE_ab14 672
`define NODE_ab15 195
`define NODE_sync 539
`define NODE_so 1672
`define NODE_clk0 1171
`define NODE_clk1out 1163
`define NODE_clk2out 421
`define NODE_rdy 89
`define NODE_nmi 1297
`define NODE_irq 103

`define NODE_dpc11_SBADD 549
`define NODE_dpc9_DBADD 859

`define NODE_a0 737
`define NODE_a1 1234
`define NODE_a2 978
`define NODE_a3 162
`define NODE_a4 727
`define NODE_a5 858
`define NODE_a6 1136
`define NODE_a7 1653

`define NODE_y0 64
`define NODE_y1 1148
`define NODE_y2 573
`define NODE_y3 305
`define NODE_y4 989
`define NODE_y5 615
`define NODE_y6 115
`define NODE_y7 843

`define NODE_x0 1216
`define NODE_x1 98
`define NODE_x2 1
`define NODE_x3 1648
`define NODE_x4 85
`define NODE_x5 589
`define NODE_x6 448
`define NODE_x7 777

`define NODE_pcl0 1139
`define NODE_pcl1 1022
`define NODE_pcl2 655
`define NODE_pcl3 1359
`define NODE_pcl4 900
`define NODE_pcl5 622
`define NODE_pcl6 377
`define NODE_pcl7 1611
`define NODE_pch0 1670
`define NODE_pch1 292
`define NODE_pch2 502
`define NODE_pch3 584
`define NODE_pch4 948
`define NODE_pch5 49
`define NODE_pch6 1551
`define NODE_pch7 205

`define NODE_Reset0 67
`define NODE_C1x5Reset 926

`define NODE_idl0 1597     // datapath signal internal data latch (driven output)
`define NODE_idl1 870
`define NODE_idl2 1066
`define NODE_idl3 464
`define NODE_idl4 1306
`define NODE_idl5 240
`define NODE_idl6 1116
`define NODE_idl7 391

`define NODE_sb0 54        // datapath bus special bus
`define NODE_sb1 1150
`define NODE_sb2 1287
`define NODE_sb3 1188
`define NODE_sb4 1405
`define NODE_sb5 166
`define NODE_sb6 1336
`define NODE_sb7 1001

`define NODE_adl0 413      // internal bus address low
`define NODE_adl1 1282
`define NODE_adl2 1242
`define NODE_adl3 684
`define NODE_adl4 1437
`define NODE_adl5 1630
`define NODE_adl6 121
`define NODE_adl7 1299

`define NODE_adh0 407      // internal bus address high
`define NODE_adh1 52
`define NODE_adh2 1651
`define NODE_adh3 315
`define NODE_adh4 1160
`define NODE_adh5 483
`define NODE_adh6 13
`define NODE_adh7 1539

`define NODE_idb0 1108     // internal bus data bus
`define NODE_idb1 991
`define NODE_idb2 1473
`define NODE_idb3 1302
`define NODE_idb4 892
`define NODE_idb5 1503
`define NODE_idb6 833
`define NODE_idb7 493

`define NODE_abl0 1096     // internal bus address bus low latched data out (inverse of inverted storage node)
`define NODE_abl1 376
`define NODE_abl2 1502
`define NODE_abl3 1250
`define NODE_abl4 1232
`define NODE_abl5 234
`define NODE_abl6 178
`define NODE_abl7 567

`define NODE_abh0 1429     // internal bus address bus high latched data out (inverse of inverted storage node)
`define NODE_abh1 713
`define NODE_abh2 287
`define NODE_abh3 422
`define NODE_abh4 1143
`define NODE_abh5 775
`define NODE_abh6 997
`define NODE_abh7 489

`define NODE_s0 1403       // machine state stack pointer
`define NODE_s1 183
`define NODE_s2 81
`define NODE_s3 1532
`define NODE_s4 1702
`define NODE_s5 1098
`define NODE_s6 1212
`define NODE_s7 1435

`define NODE_ir0 328       // internal state instruction register
`define NODE_ir1 1626
`define NODE_ir2 1384
`define NODE_ir3 1576
`define NODE_ir4 1112
`define NODE_ir5 1329      // ir5 distinguishes branch set from branch clear
`define NODE_ir6 337
`define NODE_ir7 1328

`define NODE_clock1 1536   // internal state timing control aka #T0
`define NODE_clock2 156    // internal state timing control aka #T+
`define NODE_t2 971        // internal state timing control
`define NODE_t3 1567
`define NODE_t4 690
`define NODE_t5 909

`define NODE_alu0 401
`define NODE_alu1 872
`define NODE_alu2 1637
`define NODE_alu3 1414
`define NODE_alu4 606
`define NODE_alu5 314
`define NODE_alu6 331
`define NODE_alu7 765

`define NODE_alua0 1167
`define NODE_alua1 1248
`define NODE_alua2 1332
`define NODE_alua3 1680
`define NODE_alua4 1142
`define NODE_alua5 530
`define NODE_alua6 1627
`define NODE_alua7 1522

`define NODE_alub0 977
`define NODE_alub1 1432
`define NODE_alub2 704
`define NODE_alub3 96
`define NODE_alub4 1645
`define NODE_alub5 1678
`define NODE_alub6 235
`define NODE_alub7 1535
